---
- name: Deploy k8s master node
  hosts: kube_master
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: kube
      tasks_from: install_master


- name: Deploy k8s slave nodes
  hosts: kube_slaves
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: kube
      tasks_from: install_slaves